# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests, re
__version__ = "0.2.1"
__beta__ = False


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(642, 472)
        self.ServerInfoTitle = QtWidgets.QLabel(Widget)
        self.ServerInfoTitle.setGeometry(QtCore.QRect(10, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ServerInfoTitle.setFont(font)
        self.ServerInfoTitle.setObjectName("ServerInfoTitle")

        self.updateButton = QtWidgets.QPushButton(Widget)
        self.updateButton.setGeometry(QtCore.QRect(470, 10, 161, 21))
        self.updateButton.setObjectName("updateButton")

        self.start = QtWidgets.QPushButton(Widget)
        self.start.setGeometry(QtCore.QRect(550, 50, 81, 21))
        self.start.setObjectName("updateButton_2")

        self.stop = QtWidgets.QPushButton(Widget)
        self.stop.setGeometry(QtCore.QRect(550, 80, 81, 21))
        self.stop.setObjectName("updateButton_3")
        
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(20, 50, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_6 = QtWidgets.QLabel(Widget)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.label_5 = QtWidgets.QLabel(Widget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.label_8 = QtWidgets.QLabel(Widget)
        self.label_8.setGeometry(QtCore.QRect(120, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(Widget)
        self.label_9.setGeometry(QtCore.QRect(160, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(Widget)
        self.label_10.setGeometry(QtCore.QRect(90, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(Widget)
        self.label_11.setGeometry(QtCore.QRect(100, 140, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(Widget)
        self.label_12.setGeometry(QtCore.QRect(170, 170, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        
        self.retranslateUi(Widget)
        self.checkForUpdate()
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.ServerInfoTitle.setText(_translate("Widget", "Server Information"))
        self.updateButton.setText(_translate("Widget", "PushButton"))
        self.start.setText(_translate("Widget", "Start Server"))
        self.stop.setText(_translate("Widget", "Stop Server"))
        self.label.setText(_translate("Widget", "Server Name: "))
        self.label_2.setText(_translate("Widget", "Total Server Uptime: "))
        self.label_3.setText(_translate("Widget", "Crashes:"))
        self.label_4.setText(_translate("Widget", "Mod Client:"))
        self.label_6.setText(_translate("Widget", "Total Advancements:"))
        self.label_5.setText(_translate("Widget", "Server Activity"))
        self.label_8.setText(_translate("Widget", "TextLabel"))
        self.label_9.setText(_translate("Widget", "TextLabel"))
        self.label_10.setText(_translate("Widget", "TextLabel"))
        self.label_11.setText(_translate("Widget", "TextLabel"))
        self.label_12.setText(_translate("Widget", "TextLabel"))
    
    def checkForUpdate(self):
        _translate = QtCore.QCoreApplication.translate
        self.updateButton.setDisabled(True)
        self.updateButton.setText(_translate("Widget", "Checking for update..."))

        try:
            r = requests.get("https://raw.githubusercontent.com/Silveridge/Minecraft-Server-Management-System/main/main.py")

            remoteVersion = str(re.findall('__version__ = "(.*)"', r.text)[0])
            localVersion = __version__

            print(remoteVersion)
            print(localVersion)

            if __beta__:
                self.updateButton.setText(_translate("Widget", "Update Beta Version"))
                self.updateButton.setDisabled(False)
            else:
                if remoteVersion != localVersion:
                    self.updateButton.setDisabled(False)
                    self.updateButton.setText(_translate("Widget", "Update Available!"))
                else:
                    self.updateButton.setText(_translate("Widget", "No update available"))
        except Exception as e:
            print("Update search failed, aborting.")